# Development environment variables

# Spring configuration
spring:
  application:
    name: Maktab
  datasource:
    url: jdbc:postgresql://localhost:5432/maktab
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

# Server configuration
server:
  port: 3000

# Secret values
secret:
  my-key: my-value
  jwt-secret: example
