# Development environment variables

# Spring configuration
spring:
  application:
    name: Maktab
  datasource:
    url: jdbc:postgresql://localhost:5432/maktab
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  cloud:
    aws:
      region:
        static: default
      s3:
        enabled: true
        endpoint: https://maktab-public.s3.ir-thr-at1.arvanstorage.ir
        region: default
      credentials:
        access-key: c6808f38-0cb0-4745-b43e-7f8f2380c3c7
        secret-key: 784244c50c6bfb6ea8a1e1bb8b7fbb25ebbd8f3066f31fcd3746ebbadece71ae
logging:
  level:
    io:
      awspring:
        cloud: DEBUG

# Server configurationw
server:
  port: 3000
  servlet:
    context-path: /api

# Secret values
secret:
  jwt:
    access-token:
      key: advanced-access-token-key-more-than-256-bits
      expire: 3600000 # 1 hour
    refresh-token:
      key: advanced-refresh-token-key-more-than-256-bits
      expire: 86400000 # 1 day