# Production environment variables

# Spring configuration
spring:
  application:
    name: Maktab
  datasource:
    url: ${PRIMARY_DB_URI}
    username: ${PRIMARY_DB_USER}
    password: ${PRIMARY_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  cloud:
    aws:
      s3:
        enabled: true
        endpoint: s3.ir-thr-at1.arvanstorage.ir
      credentials:
        access-key:
        secret-key:

# Server configuration
server:
  port: ${SERVER_MAIN_PORT}
  servlet:
    context-path: /api

# Secret values
secret:
  jwt:
    access-token:
      key: ${JWT_ACCESS_TOKEN_KEY}
      expire: ${JWT_ACCESS_TOKEN_EXPIRE}
    refresh-token:
      key: ${JWT_REFRESH_TOKEN_KEY}
      expire: ${JWT_REFRESH_TOKEN_EXPIRE}
