# Production environment variables

# Spring configuration
spring:
  application:
    name: Maktab
  datasource:
    url: jdbc:postgresql://localhost:5432/maktab
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none

# Server configuration
server:
  port: 80
  servlet:
    context-path: /api

# Secret values
secret:
  jwt:
    access-token:
      key: ${JWT_ACCESS_TOKEN_KEY}
      expire: ${JWT_ACCESS_TOKEN_EXPIRE}
    refresh-token:
      key: ${JWT_REFRESH_TOKEN_KEY}
      expire: ${JWT_REFRESH_TOKEN_EXPIRE}
