# Development environment variables

# Spring configuration
spring:
  application:
    name: Maktab
  datasource:
    url: jdbc:postgresql://localhost:5432/maktab
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

# Server configuration
server:
  port: 3000
  servlet:
    context-path: /api

# Secret values
secret:
  jwt:
    access-token:
      key: advanced-access-token-key-more-than-256-bits
      expire: 3600000 # 1 hour
    refresh-token:
      key: advanced-refresh-token-key-more-than-256-bits
      expire: 86400000 # 1 day