# Development environment variables

# Spring configuration
spring:
  profiles:
    include: policy
  application:
    name: Maktab
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/maktab
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  cloud:
    aws:
      s3:
        enabled: true
        endpoint: https://s3.ir-thr-at1.arvanstorage.ir
        region: aws-global
      credentials:
        access-key: c6808f38-0cb0-4745-b43e-7f8f2380c3c7
        secret-key: 89a82f1b9d38074302a5f3d524ab484787946c8dbbe1b53637792bd7829beb94

# Server configuration
server:
  port: 3000
  servlet:
    context-path: /api

# Secret values
secret:
  jwt:
    access-token:
      key: advanced-access-token-key-more-than-256-bits
      expire: 3600000 # 1 hour
    refresh-token:
      key: advanced-refresh-token-key-more-than-256-bits
      expire: 86400000 # 1 day