# Production environment variables

# Spring configuration
spring:
  application:
    name: Maktab
  datasource:
    url: jdbc:postgresql://localhost:5432/maktab
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none

# Server configuration
server:
  port: 80
  servlet:
    context-path: /api

# Secret values
secret:
  my-key: my-value
  jwt-secret: better-example-key

